{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginxlocal.serviceAccountName" . }}
  labels:
{{ include "nginxlocal.labels" . | nindent 4 }}
{{- end -}}
